name: Windows Parsec Remote

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    
    steps:
    - name: Install Parsec
      run: |
        # Parsec indir (gaming remote desktop)
        Invoke-WebRequest https://builds.parsecgaming.com/package/parsec-windows.exe -OutFile parsec.exe
        
        # Sessiz kurulum
        Start-Process -FilePath parsec.exe -ArgumentList "/S" -Wait
        
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "PARSEC KURULDU!" -ForegroundColor Yellow
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "1. https://parsec.app adresinden hesap açın" -ForegroundColor Cyan
        Write-Host "2. Parsec uygulamasını telefonunuza indirin" -ForegroundColor Cyan
        Write-Host "3. Bu bilgisayar otomatik görünecek" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Sistem Bilgisi:" -ForegroundColor Yellow
        Write-Host "OS: Windows Server 2022" -ForegroundColor White
        Write-Host "CPU: 2 cores" -ForegroundColor White
        Write-Host "RAM: 7 GB" -ForegroundColor White
        Write-Host "========================================" -ForegroundColor Green
        
    - name: Create User
      run: |
        net user parsecuser "Parsec123!" /add
        net localgroup administrators parsecuser /add
        
    - name: Keep Alive
      run: Start-Sleep -Seconds 21600
