name: Windows AnyDesk

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    
    steps:
    - name: Setup AnyDesk
      run: |
        # AnyDesk indir
        Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile AnyDesk.exe
        
        # Yükle ve başlat
        Start-Process AnyDesk.exe -ArgumentList "--install C:\AnyDesk --start-with-win --silent" -Wait
        Start-Sleep -Seconds 10
        
        # Şifre ayarla
        & "C:\AnyDesk\AnyDesk.exe" --set-password "GitHubRDP123"
        
        # ID'yi al
        $id = & "C:\AnyDesk\AnyDesk.exe" --get-id
        
        Write-Host "========================================" -ForegroundColor Green
        Write-Host "ANYDESK HAZIR!" -ForegroundColor Yellow  
        Write-Host "========================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "AnyDesk ID: $id" -ForegroundColor Cyan
        Write-Host "Şifre: GitHubRDP123" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "https://anydesk.com/download" -ForegroundColor White
        Write-Host "========================================" -ForegroundColor Green
        
    - name: Keep Running
      run: |
        while ($true) {
          Write-Host "AnyDesk çalışıyor..." -ForegroundColor Green
          Start-Sleep -Seconds 300
        }
