name: SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false  # SSH anahtarı kontrolünü kapatır
