name: En Basit Terminal

on:
  workflow_dispatch:

jobs:
  terminal:
    runs-on: ubuntu-latest

    steps:
      - name: Başlat
        run: echo "Web terminal hazır..."

      - name: 🔥 Web Terminal Bağlantısı
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
