name: Terminal Bağlantısı

on:
  workflow_dispatch:  # Manuel başlatma için

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu çek
        uses: actions/checkout@v4
      
      - name: Terminal bağlantısı kur
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Sadece sen bağlanabilirsin
